### ISSUE TITLE
User Story US05 - Realizar Pagamento 

### ISSUE THREAD

**Issue by flaviogui** [flaviogui/TechCell-Pro#12]
Descreve descrição, requisitos necessários, prioridade e testes de acesso (TA).

**Comment by LaianKevin** [comment]
Issue #12 User Story US05 - Realizar Pagamento
Adicionando User Story US05 - Realizar Pagamento

**Comment by flaviogui** [comment]
Melhore a descrição, detalhe melhor como o sistema vai realizar esse pagamento. Na parte de requisitos necessários, é necessário rever também (Elabore requisitos), e o teste de aceitação, tem que fazer quando o pagamento funciona e quando não funciona.

**Comment by flaviogui** [comment]
Está ok @LaianKevin
