### ISSUE TITLE
Modelo Conceitual - Diagrama de Classe

### ISSUE THREAD

**Issue by flaviogui** [flaviogui/TechCell-Pro#13]

**Comment by gbrl08snts** [comment]
Issue #13
Adicionei o diagrama de classes ao arquivo doc-modelos.md e atualizei a informação das entidades do diagrama nos arquivos doc-visão.md e doc-modelos.md, todas as atualizações foram feitas na minha branch.

**Comment by flaviogui** [comment]
Tá ok
