### ISSUE TITLE
Documento da Arquitetural

### ISSUE THREAD

**Issue by flaviogui** [flaviogui/TechCell-Pro#18]
Criação do Documento da Arquitetural, contendo apenas com o modelo (imagem) da Arquitetura Geral do Sistemae descreva cada parte desta arquitetura (cada camada);
Ainda não precisa ser o Documento Arquitetural completo, mas a arquitetura geral do sistema deste a tela até a base de dados;

**Comment by gbrl08snts** [comment]
Issue - #18
Criei o arquivo base do modelo de arquitetura do projeto
